//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlayListEntities : DbContext
    {
        public PlayListEntities()
            : base("name=PlayListEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<StatisticsOnStudent> StatisticsOnStudents { get; set; }
        public virtual DbSet<StudentsFeedback> StudentsFeedbacks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Week> Weeks { get; set; }
        public virtual DbSet<WordCategory> WordCategories { get; set; }
        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    }
}
