//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsFeedback
    {
        public int FeedbackCode { get; set; }
        public int StudentCode { get; set; }
        public int WordCode { get; set; }
        public int Score { get; set; }
    
        public virtual User User { get; set; }
        public virtual Word Word { get; set; }
    }
}
