//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordError
    {
        public int WordId { get; set; }
        public int StatistictToStudentsId { get; set; }
        public int NumErrors { get; set; }
    
        public virtual StatisticsOnStudent StatisticsOnStudent { get; set; }
        public virtual Word Word { get; set; }
    }
}
